<footer class="footer-layout">
        <div class="footer-column">
            <p><em>A35 Bach Dang<br>Tan Binh District<br>Ho Chi Minh City<br>Vietnam</em></p>
        </div>
        <div class="footer-column">
            <p>AI-powered Solutions<br>Machine Learning Research<br>Cloud Computing<br>Data Science</p>
        </div>
        <div class="footer-column">
            <p><strong>Acknowledgements</strong><br><a href="https://www.w3schools.com/">W3Cchools</a><br><a href="https://developer.mozilla.org/en-US/docs/Web/HTML">MDN Web Docs</a><br><a href="https://html.com/">html.com</a>
        </div>
        <div class="footer-column">
            <p>AI Ethics & Compliance<br>Big Data Processing<br>Natural Language Processing<br>AI Security</p>
        </div>
        <div class="footer-column">
            <p>Contribute<br>Innovate<br>Explore Careers<br>Tech Blog</p>
        </div>
        <div class="footer-column">
            <p>AI-driven Insights<br>Deep Learning Models<br>Tech Conferences<br>Industry Partnerships</p>
        </div>
        <div class="footer-bottom">
            <p><a href="https://youtu.be/lWndsBCuqtU">DEMO VIDEO</a></p>
            <p><a href="https://www.linkedin.com/">Linkedln</a></p>
            <p>Phone: +123-456-789<br>info@techtitans.com</p>
            <p>&copy; Tech Titans 2024. All rights reserved</p>
        </div>
    </footer>